---
title: Seminararbeit AI-assisted programming and data analysis
subtitle: Data Profiling with LLM's - A Case Study on HR Data
date-format: "D. MMMM YYYY"

author:
  - name: Vincent-Konstantin Kapp
    email: vincent.kapp@studium.uni-hamburg.de
    affiliations: 
        - id: 7778027
          name: Universität Hamburg
          department: M.Sc. BWL
          address: Street Address
          city: Hamburg
          state: State
          postal-code: Postal Code
    note: This is the author.
  - name: Prof. Dr. Martin Spindler
    email: martin.spindler@uni-hamburg.de
    affiliations:
        - id: another-u
          name: Universität Hamburg
          department: Statistik mit Anwendung in der Betriebswirtschaftslehre
          address: Street Address
          city: Hamburg
          state: State
          postal-code: Postal Code
    note: This is the Editor

keywords: 
  - LLM
  - Data Analysis
  - Data Profiling
date: last-modified
bibliography: My EndNote Library.bib
fontsize: 11pt
linestretch: 1.5
format:
  pdf:
    documentclass: article
    keep-tex: true
    titlepage: true
    geometry: 
      - "a4paper"
      - left=35mm
      - right=35mm
      - top=4cm
      - bottom=4cm
    lof: false
    lot: false
number-sections: true

execute:
    eval: true
    echo: true
    warning: false
jupyter: python3

abstract: |
  Datengetriebene Prozesse können Unternehmen nicht nur dabei helfen, ihre Prozesse zu optimieren, sondern auch bei der Entwicklung neuer Strategien. Um festzustellen, welche Daten in den Datenbanken vorliegen und wie diese zueinander stehen, braucht es Mitarbeiter*innen, die einzeln überprüfen, welche Daten vorhanden sind und in welchen Zusammenhängen sie basierend auf Common Sense existieren. Data Profiling stellt Unternehmen mit historisch gewachsenen Datenbanksystemen vor Herausforderungen für die datengestützte Transformation. Können die aktuellen Entwicklungen von Large Language Modellen (LLMs) dazu beitragen, automatisiert die Zusammenhänge von Spalten zu erkennen? Um diese Frage zu beantworten, widmet sich diese Seminararbeit, aufbauend auf der Arbeit von Trummer (2024), der Untersuchung, wie gut LLMs anhand einer Case Study die Korrelation von Daten erkennen können.
---

# Einleitung

# Hintergrund

## Data Profiling

## Korrelationserkennung in Datenbanken
[@RN5578].

## Sprachmodelle und deren Anwendung in der Datenanalyse
[@RN5576].

# Methodik der Fallstudie

## Datenbasis und Vorbereitung

## Vorgehensweise zur Korrelationsanalyse mit LLM

## Benchmark und Bewertungsmetriken

# Durchführung der Fallstudie: Gender-Pay-Gap-Analyse
Meine Überlegung ist es das Ergebnisse von [@bach2024heterogeneity].

## Fragestellung

## Implementierung des LLM für Korrelationserkennung

## Benchmarking-Ergebnisse

# Vergleich und Auswertung der Ergebnisse

## Vergleich der Ergebnisse mit Prompoting

## Szenariobasierte Auswertung

## Bewertung der Korrelationserkennung

# Diskussion der Ergebnisse und Implikationen

## Interpretation der Ergebnisse

## Limitationen

## Praktische Anwendungsmöglichkeit

# Fazit und Ausblick

# References {-}